### ISSUE TITLE
I have some problem with mock api

### ISSUE THREAD

**Issue by Aspedm** [Lusito/mockzilla-webextension#3]
1. Cannot find name 'mockBrowser'. ts(2304)

I have some helpers and simply test. All works fine only with dirty hack `(global as any)`

helpers/main.ts
```typescript
export const getBgPage = (): Window => {
    return browser.extension.getBackgroundPage();
};

export const getManifest = (): Manifest.WebExtensionManifest => {
    return browser.runtime.getManifest();
}
```

helpers.test.ts
```typescript
import { getBgPage, getManifest } from '../index';

describe('Main helpers', () => {
    it ('Get background page', () => {
        const win = window;

        (global as any).mockBrowser.extension.getBackgroundPage.expect().andReturn(win);
        expect(getBgPage()).toEqual(win);
    });

    it ('Get manifest', () => {
        const manifest = {
            homepage_url: 'https://some-url.com',
            author: 'Web ext',
            version: '0.0.1',
        };

        (global as any).mockBrowser.runtime.getManifest.expect().andReturn(manifest);
        expect(getManifest()).toEqual(manifest);
    });
});
```

In `setupTests.ts` I add `import 'mockzilla-webextension';`. 

2. Mock "browser.runtime" is not implemented

I have diferrents react components and helpers where imported main/helpers.ts. I'm trying test some function but have exception "Mock "browser.runtime" is not implemented" or "Cannot read property {some api method} of undefined" on getManifest or getBgPage functions. 

Packages:
- webextension-polyfill-ts (0.21.0)
- mockzilla-webextension (0.7.0)
- mockzilla (0.8.0)

Thx =)

**Comment by Lusito** [comment]
global as any should not be required. This project automatically declares types, to that this hack should not be necessary.

1. Make sure you have your jest config set up correctly and are using a recent typescript version:
https://lusito.github.io/mockzilla-webextension/setup.html#jest

2. The message "Mock .... is not implemented" suggests, that you didn't prepare an `.expect()` statement in advance.

3. This library was meant to create unit-tests of your logic code. Ideally, you'd separate your UI (react) from that logic and test the UI separately, since testing it together might be difficult.

Can't tell you much more without seeing a lot more of your code setup. Is your repo online somewhere?

**Comment by Aspedm** [comment]
Yep. Config is correctly and using actual lib versions. I thought also, but is not fixed problem.
What about react. React component not have any logic with browser api. All events through runtime.sendMessage sended to background.  I want test what some method called runtime.sendMessage with some arguments. Apparently I just mock all method in react.

Unfortunately this is project on my job. I can create some demo. Where is prefer for you?
